-- Adds FeatureFlag: a named switch an app reads at launch, delivered in the
-- /sdk/version/check response so it reaches already-published binaries.
--
-- Hand-written rather than generated by `prisma migrate dev`, because the
-- databases live on the VPS with `listen_addresses = localhost` and are not
-- reachable from a developer machine. Kept deliberately narrow so it can be read
-- and checked by eye: one CREATE TABLE, one unique index, one plain index, one
-- foreign key. Nothing here touches an existing table, so it cannot fail on
-- populated data and has no effect on any current row.
--
-- Verify the chain still reproduces schema.prisma (empty output means correct):
--   npx prisma migrate diff --from-schema-datasource prisma/schema.prisma \
--                           --to-schema-datamodel  prisma/schema.prisma --script

-- CreateTable
CREATE TABLE "FeatureFlag" (
    "id" TEXT NOT NULL,
    "appId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    -- "all" means every platform. A non-null column with a default, not a
    -- nullable one: Postgres treats NULLs as distinct in a unique index, so a
    -- nullable column would accept two "every platform" rows for one key and then
    -- serve whichever the query returned first.
    "platform" TEXT NOT NULL DEFAULT 'all',
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FeatureFlag_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "FeatureFlag_appId_key_platform_key" ON "FeatureFlag"("appId", "key", "platform");

-- CreateIndex
CREATE INDEX "FeatureFlag_appId_idx" ON "FeatureFlag"("appId");

-- AddForeignKey
ALTER TABLE "FeatureFlag" ADD CONSTRAINT "FeatureFlag_appId_fkey" FOREIGN KEY ("appId") REFERENCES "App"("id") ON DELETE CASCADE ON UPDATE CASCADE;
